[Unit]
# Ensure SRS keeps trying to come back even if it crashes repeatedly.
# Disable start-rate limiting.
StartLimitIntervalSec=0
StartLimitBurst=0

[Service]
# Keep trying forever.
Restart=always
RestartSec=2
# Be tolerant to slow start/stop.
TimeoutStartSec=30
TimeoutStopSec=10
